from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from app.mcp.server import MCPServer

from app.mcp.webautomation.services.webautomation_mcp_service import WebAutomationMCPService


def register_webautomation_tools(server: MCPServer) -> None:
    service = WebAutomationMCPService()

    server.register_tool(name="web_open_url", description="Open a URL in a Playwright browser session.", handler=service.web_open_url, input_schema={"type": "object", "properties": {"url": {"type": "string"}}, "required": ["url"]}, tags=["webautomation", "web", "open", "read"])
    server.register_tool(name="web_get_title", description="Open a URL and return the page title.", handler=service.web_get_title, input_schema={"type": "object", "properties": {"url": {"type": "string"}}, "required": ["url"]}, tags=["webautomation", "web", "title", "read"])
    server.register_tool(name="web_extract_text", description="Open a URL and extract visible page text.", handler=service.web_extract_text, input_schema={"type": "object", "properties": {"url": {"type": "string"}}, "required": ["url"]}, tags=["webautomation", "web", "extract", "text", "read"])
    server.register_tool(name="web_capture_page", description="Open a URL and save a page screenshot.", handler=service.web_capture_page, input_schema={"type": "object", "properties": {"url": {"type": "string"}, "full_page": {"type": "boolean", "default": False}}, "required": ["url"]}, tags=["webautomation", "web", "screenshot", "capture", "read"])
    server.register_tool(name="web_save_page_html", description="Open a URL and save the page HTML into runtime/web/pages.", handler=service.web_save_page_html, input_schema={"type": "object", "properties": {"url": {"type": "string"}, "name_prefix": {"type": "string", "default": "page"}}, "required": ["url"]}, tags=["webautomation", "web", "save", "html", "read"])
    server.register_tool(name="web_save_page_text", description="Open a URL and save the visible page text into runtime/web/pages.", handler=service.web_save_page_text, input_schema={"type": "object", "properties": {"url": {"type": "string"}, "name_prefix": {"type": "string", "default": "page"}}, "required": ["url"]}, tags=["webautomation", "web", "save", "text", "read"])
    server.register_tool(name="web_search_duckduckgo", description="Run a simple DuckDuckGo browser search with Playwright.", handler=service.web_search_duckduckgo, input_schema={"type": "object", "properties": {"query": {"type": "string"}}, "required": ["query"]}, tags=["webautomation", "web", "search", "duckduckgo", "read"])
    server.register_tool(name="web_click", description="Open a URL and click the first matching selector.", handler=service.web_click, input_schema={"type": "object", "properties": {"url": {"type": "string"}, "selector": {"type": "string"}, "wait_after_ms": {"type": "integer", "default": 0}}, "required": ["url", "selector"]}, tags=["webautomation", "web", "click", "interaction"])
    server.register_tool(name="web_type", description="Open a URL and type into the first matching selector.", handler=service.web_type, input_schema={"type": "object", "properties": {"url": {"type": "string"}, "selector": {"type": "string"}, "text": {"type": "string"}, "clear_first": {"type": "boolean", "default": True}}, "required": ["url", "selector", "text"]}, tags=["webautomation", "web", "type", "interaction"])
    server.register_tool(name="web_press_key", description="Open a URL and press a keyboard key.", handler=service.web_press_key, input_schema={"type": "object", "properties": {"url": {"type": "string"}, "key": {"type": "string"}, "wait_after_ms": {"type": "integer", "default": 0}}, "required": ["url", "key"]}, tags=["webautomation", "web", "keyboard", "interaction"])
    server.register_tool(name="web_open_and_capture", description="Open a URL, optionally wait, and save a screenshot.", handler=service.web_open_and_capture, input_schema={"type": "object", "properties": {"url": {"type": "string"}, "full_page": {"type": "boolean", "default": False}, "wait_after_ms": {"type": "integer", "default": 0}}, "required": ["url"]}, tags=["webautomation", "web", "open", "capture", "interaction"])
    server.register_tool(name="web_type_and_press", description="Open a URL, type into a selector, press a key, and optionally wait.", handler=service.web_type_and_press, input_schema={"type": "object", "properties": {"url": {"type": "string"}, "selector": {"type": "string"}, "text": {"type": "string"}, "key": {"type": "string", "default": "Enter"}, "clear_first": {"type": "boolean", "default": True}, "wait_after_ms": {"type": "integer", "default": 1000}}, "required": ["url", "selector", "text"]}, tags=["webautomation", "web", "type", "keyboard", "interaction"])
    server.register_tool(name="web_search_and_capture", description="Run a DuckDuckGo search, optionally wait, and save a screenshot.", handler=service.web_search_and_capture, input_schema={"type": "object", "properties": {"query": {"type": "string"}, "full_page": {"type": "boolean", "default": False}, "wait_after_ms": {"type": "integer", "default": 1200}}, "required": ["query"]}, tags=["webautomation", "web", "search", "capture", "duckduckgo"])
    server.register_tool(name="web_search_and_extract", description="Run a DuckDuckGo search, optionally wait, and extract visible text.", handler=service.web_search_and_extract, input_schema={"type": "object", "properties": {"query": {"type": "string"}, "wait_after_ms": {"type": "integer", "default": 1200}}, "required": ["query"]}, tags=["webautomation", "web", "search", "extract", "duckduckgo"])

    server.register_tool(name="web_session_start", description="Start a persistent Playwright web session and optionally open a URL.", handler=service.web_session_start, input_schema={"type": "object", "properties": {"url": {"type": "string", "default": ""}}}, tags=["webautomation", "web", "session", "start"])
    server.register_tool(name="web_session_stop", description="Stop a persistent Playwright web session.", handler=service.web_session_stop, input_schema={"type": "object", "properties": {"session_id": {"type": "string"}}, "required": ["session_id"]}, tags=["webautomation", "web", "session", "stop"])
    server.register_tool(name="web_session_info", description="Read current URL and title from a persistent Playwright web session.", handler=service.web_session_info, input_schema={"type": "object", "properties": {"session_id": {"type": "string"}}, "required": ["session_id"]}, tags=["webautomation", "web", "session", "read"])
    server.register_tool(name="web_session_open_url", description="Open a URL in a persistent Playwright web session.", handler=service.web_session_open_url, input_schema={"type": "object", "properties": {"session_id": {"type": "string"}, "url": {"type": "string"}}, "required": ["session_id", "url"]}, tags=["webautomation", "web", "session", "open"])
    server.register_tool(name="web_session_type", description="Type into a selector inside a persistent Playwright web session.", handler=service.web_session_type, input_schema={"type": "object", "properties": {"session_id": {"type": "string"}, "selector": {"type": "string"}, "text": {"type": "string"}, "clear_first": {"type": "boolean", "default": True}}, "required": ["session_id", "selector", "text"]}, tags=["webautomation", "web", "session", "type"])
    server.register_tool(name="web_session_click", description="Click a selector inside a persistent Playwright web session.", handler=service.web_session_click, input_schema={"type": "object", "properties": {"session_id": {"type": "string"}, "selector": {"type": "string"}, "wait_after_ms": {"type": "integer", "default": 0}}, "required": ["session_id", "selector"]}, tags=["webautomation", "web", "session", "click"])
    server.register_tool(name="web_session_press_key", description="Press a keyboard key inside a persistent Playwright web session.", handler=service.web_session_press_key, input_schema={"type": "object", "properties": {"session_id": {"type": "string"}, "key": {"type": "string"}, "wait_after_ms": {"type": "integer", "default": 0}}, "required": ["session_id", "key"]}, tags=["webautomation", "web", "session", "keyboard"])
    server.register_tool(name="web_session_extract_text", description="Extract visible page text from a persistent Playwright web session.", handler=service.web_session_extract_text, input_schema={"type": "object", "properties": {"session_id": {"type": "string"}}, "required": ["session_id"]}, tags=["webautomation", "web", "session", "extract"])
    server.register_tool(name="web_session_capture_page", description="Capture a screenshot from a persistent Playwright web session.", handler=service.web_session_capture_page, input_schema={"type": "object", "properties": {"session_id": {"type": "string"}, "full_page": {"type": "boolean", "default": False}}, "required": ["session_id"]}, tags=["webautomation", "web", "session", "capture"])
    server.register_tool(name="web_session_list", description="List active persistent Playwright web sessions in the current process.", handler=service.web_session_list, input_schema={"type": "object", "properties": {}}, tags=["webautomation", "web", "session", "list"])
    server.register_tool(name="web_session_stop_all", description="Stop all active persistent Playwright web sessions in the current process.", handler=service.web_session_stop_all, input_schema={"type": "object", "properties": {}}, tags=["webautomation", "web", "session", "stop_all"])