from __future__ import annotations

from .inputfeed_settings import (
    INPUTFEED_CHUNK_SECONDS,
    INPUTFEED_DEDUP_SECONDS,
    INPUTFEED_ENABLE_SILERO_VAD,
    INPUTFEED_MIN_RMS,
    INPUTFEED_SILERO_MIN_SEGMENTS,
    INPUTFEED_SILERO_MIN_SPEECH_MS,
    INPUTFEED_SILERO_MIN_SILENCE_MS,
    INPUTFEED_SILERO_SPEECH_PAD_MS,
    INPUTFEED_SILERO_THRESHOLD,
    INPUTFEED_STREAM_COMMIT_STABLE_PASSES,
    INPUTFEED_STREAM_MAX_BUFFER_SECONDS,
    INPUTFEED_STREAM_OVERLAP_SECONDS,
    INPUTFEED_STREAM_RECENT_SEGMENT_COUNT,
    INPUTFEED_STREAM_STEP_SECONDS,
    INPUTFEED_STT_BACKEND,
    INPUTFEED_USE_STREAMING,
    INPUTFEED_CHANNELS,
    INPUTFEED_SAMPLE_RATE,
    INPUTFEED_SAMPLE_WIDTH,
    INPUTFEED_TO_TEXT_STATUS_JSON,
    LIVE_TRANSCRIPT_ASSEMBLED_JSONL,
    LIVE_TRANSCRIPT_ASSEMBLED_LATEST_JSON,
    LIVE_TRANSCRIPT_HISTORY_JSONL,
    LIVE_TRANSCRIPT_LATEST_JSON,
    LIVE_TRANSCRIPT_RAW_JSONL,
    LIVE_TRANSCRIPT_RAW_LATEST_JSON,
    RUNTIME_ARCHIVE_DIR,
    RUNTIME_DIR,
    RUNTIME_SACRED_DIR,
    RUNTIME_STATUS_DIR,
    STT_BEAM_SIZE,
    STT_COMPUTE_TYPE,
    STT_LANGUAGE,
    STT_MODEL,
    STT_VAD_FILTER,
    STT_CHUNK_MS,
    TRANSCRIPT_SESSION_ID,
    TRANSCRIPT_SOURCE_NAME,
    TRANSCRIPT_SOURCE_TYPE,
)

MODULE_DIR = RUNTIME_DIR.parent / "app" / "inputfeed_to_text"
APP_DIR = MODULE_DIR.parent
PROJECT_ROOT = APP_DIR.parent

SESSION_ID = TRANSCRIPT_SESSION_ID
SOURCE_NAME = TRANSCRIPT_SOURCE_NAME
SOURCE_TYPE = TRANSCRIPT_SOURCE_TYPE

INPUT_SAMPLE_RATE = INPUTFEED_SAMPLE_RATE
INPUT_CHANNELS = INPUTFEED_CHANNELS
SAMPLE_WIDTH = INPUTFEED_SAMPLE_WIDTH

CHUNK_SECONDS = INPUTFEED_CHUNK_SECONDS